const $=s=>document.querySelector(s),app=$("#app"),K="TKPRPG_FINAL_SAVE";
const HERO={劉備:[460,38,"仁德劍"],關羽:[620,32,"青龍刀"],張飛:[660,28,"蛇矛"],趙雲:[590,34,"龍膽槍"],諸葛亮:[410,65,"羽扇"],黃忠:[540,30,"強弓"],馬超:[610,29,"鐵騎槍"]};
const chapters=["桃園起兵","黃巾平定","虎牢雄關","臥龍出山","赤壁烈火","漢中爭鋒","北伐中原","天下歸一"];
const maps=[
["################","#....tt....C...#","#..~~~~........#","#..~~~~..tt....#","#..............#","#...tt.........#","#......@.......#","#..........C...#","#..^^^^........#","#..^^^^...tt...#","#..............#","################"],
["################","#C.....tt......#","#..~~~~....^^..#","#..~~~~....^^..#","#.....tt.......#","#..........C...#","#......@.......#","#...^^^^.......#","#...^^^^..tt...#","#..............#","#..C...........#","################"]];
const tileClass={"#":"tree",".":"grass","~":"water","^":"mount","C":"castle","t":"woods","@":"grass"};
let S,party,enemies=[],audio=null;
function fresh(){S={scene:"title",x:7,y:6,map:0,gold:180,food:800,sp:48,maxSp:48,exp:0,chapter:0,turn:1,menu:0,items:{藥草:4,火把:2,回復丹:1},flags:{boss:false},msg:"漢室衰微，群雄並起。"};party=["劉備","關羽","張飛"].map(unit)}
function unit(n){let d=HERO[n]||[300,20,"鐵劍"];return{name:n,hp:d[0],max:d[0],int:d[1],weapon:d[2],lv:1,exp:0,dead:false}}
fresh();
function beep(f=220,d=.06){try{audio??=new AudioContext();let o=audio.createOscillator(),g=audio.createGain();o.type="square";o.frequency.value=f;g.gain.value=.035;o.connect(g);g.connect(audio.destination);o.start();g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+d);o.stop(audio.currentTime+d)}catch{}}
function save(){localStorage.setItem(K,JSON.stringify({S,party}));toast("進度已儲存")}
function load(){let d=localStorage.getItem(K);if(!d)return false;try{let x=JSON.parse(d);S=x.S;party=x.party;S.scene="world";world();return true}catch{return false}}
function px(name,bad=false){let c=bad?["#c54438","#6b2424"]:name==="關羽"?["#d83b35","#319052"]:name==="張飛"?["#8249a1","#a94237"]:name==="趙雲"?["#ddd","#527cad"]:name==="諸葛亮"?["#eee","#6558a4"]:name==="劉備"?["#d6bc42","#568d48"]:["#d3a03a","#567e9b"];return `<div class="sprite ${bad?"bad":""}" style="--a:${c[0]};--b:${c[1]}"><i class="plume"></i><i class="hair"></i><i class="face"></i><i class="body"></i><i class="hand"></i><i class="weapon"></i><i class="foot f1"></i><i class="foot f2"></i></div>`}
function frame(x,cls=""){app.innerHTML=`<div class="cab"><div class="screen ${cls}">${x}</div><div class="footbar">THREE KINGDOMS PIXEL RPG · FINAL EDITION · v3.0.0.0</div></div>`}
function title(){S.scene="title";frame(`<section class="title"><div class="sun"></div><h1>三國志<em>群雄傳</em></h1><h2>THREE KINGDOMS<br>PIXEL RPG</h2><div class="titlemenu"><button id="new">▶ 新的冒險</button><button id="continue">　繼續遊戲</button></div><p>方向鍵 / WASD 移動　Enter 確認　M 選單　S 儲存</p></section>`);$("#new").onclick=()=>{fresh();S.scene="world";world()};$("#continue").onclick=()=>load()||toast("尚無存檔")}
function world(){S.scene="world";let m=maps[S.map],tiles=m.flatMap((r,y)=>[...r].map((c,x)=>`<i class="tile ${tileClass[c]}" data-x="${x}" data-y="${y}"></i>`)).join("");frame(`<section class="world"><div class="map">${tiles}<div class="player" style="left:${S.x*32}px;top:${S.y*32}px">${px(party[0].name)}</div></div><aside><b>第${S.chapter+1}章</b><strong>${chapters[S.chapter]}</strong><hr>金 ${S.gold}<br>糧 ${S.food}<br>SP ${S.sp}/${S.maxSp}<hr>隊伍 ${party.length}/5<br><small>S 儲存<br>M 主選單</small></aside><div class="dialog">${S.msg}<br><small>前往城池可休息、購物、推進劇情。</small></div></section>`);document.querySelectorAll(".castle").forEach(t=>t.onclick=()=>town())}
function walk(dx,dy){let m=maps[S.map],nx=S.x+dx,ny=S.y+dy,c=m[ny]?.[nx];if(!c||"#~^".includes(c))return;S.x=nx;S.y=ny;beep(90,.025);if(c==="C"){town();return}world();if(Math.random()<.14)setTimeout(()=>battle(false),100)}
function town(){S.scene="town";let recruit=S.chapter>=2&&!party.some(x=>x.name==="趙雲")?"趙雲":S.chapter>=3&&!party.some(x=>x.name==="諸葛亮")?"諸葛亮":null;frame(`<section class="town"><h2>🏯 漢軍城寨</h2><div class="npc">${px(recruit||"劉備")}<p>${recruit?`${recruit}：久聞玄德仁義，願效犬馬之勞。`:"軍師：整備兵馬後，再繼續征途吧。"}</p></div><div class="townmenu"><button data-a="rest">客棧　金30</button><button data-a="shop">商店</button>${recruit?'<button data-a="recruit">招募武將</button>':""}<button data-a="boss">挑戰本章主將</button><button data-a="leave">離開城寨</button></div></section>`);document.querySelectorAll("[data-a]").forEach(b=>b.onclick=()=>townAction(b.dataset.a,recruit))}
function townAction(a,r){if(a==="leave"){S.msg="軍隊離開城寨。";world()}if(a==="rest"){if(S.gold<30)return toast("金不足");S.gold-=30;party.forEach(p=>{p.hp=p.max;p.dead=false});S.sp=S.maxSp;toast("全軍恢復！");town()}if(a==="shop"){if(S.gold<20)return toast("金不足");S.gold-=20;S.items.藥草++;toast("購買藥草 ×1");town()}if(a==="recruit"&&r){party.push(unit(r));toast(r+"加入隊伍！");town()}if(a==="boss")battle(true)}
function enemySet(boss){let bossNames=["張角","華雄","呂布","曹仁","曹操","夏侯淵","司馬懿","司馬昭"],n=boss?bossNames[S.chapter]:["黃巾兵","山賊","曹軍兵","魏軍兵"][Math.min(3,Math.floor(S.chapter/2))];enemies=Array.from({length:boss?5:3},(_,i)=>({name:i===0?n:n+"卒",hp:(boss&&i===0?650:180)+S.chapter*90,max:(boss&&i===0?650:180)+S.chapter*90,dead:false,boss:boss&&i===0}))}
function battle(boss=false){S.scene="battle";S.bossBattle=boss;enemySet(boss);S.msg=boss?"敵軍主將出陣！":"敵軍出現！";S.menu=0;battleView()}
function living(a){return a.filter(x=>!x.dead)}
function warrior(u,bad=false){let pc=Math.max(0,u.hp/u.max*100);return `<div class="warrior ${bad?"enemy":""} ${u.dead?"dead":""}">${bad?"":px(u.name)}<div><b>${u.name}</b><span>${Math.max(0,u.hp)}</span><em><i style="width:${pc}%"></i></em></div>${bad?px(u.name,true):""}</div>`}
function battleView(){frame(`<section class="battle"><header>${chapters[S.chapter]}　ROUND ${S.turn}</header><div class="teams"><div>${party.slice(0,5).map(x=>warrior(x)).join("")}</div><i class="vs">⚔</i><div>${enemies.map(x=>warrior(x,true)).join("")}</div></div><div class="battleui"><div class="portrait">${px(party[0].name)}<b>${party[0].name}</b></div><div class="cmd"><p>${S.msg}</p>${["攻擊","火計 SP5","回復 SP6","總攻擊","道具","撤退"].map((x,i)=>`<button data-c="${i}">${i===S.menu?"▶":"　"}${x}</button>`).join("")}</div><div class="resource">SP ${S.sp}<br>金 ${S.gold}<br>糧 ${S.food}</div></div></section>`);document.querySelectorAll("[data-c]").forEach(b=>b.onclick=()=>command(+b.dataset.c))}
function command(i){if(i===5&&!S.bossBattle){S.msg="成功撤退！";world();return}if(i===4){if(!S.items.藥草)return toast("沒有藥草");S.items.藥草--;let p=living(party).sort((a,b)=>a.hp-b.hp)[0];p.hp=Math.min(p.max,p.hp+160);S.msg=`${p.name} 使用藥草，恢復兵力！`;battleView();return setTimeout(enemyTurn,450)}if(i===2){if(S.sp<6)return toast("SP不足");S.sp-=6;let p=living(party).sort((a,b)=>a.hp/a.max-b.hp/b.max)[0];p.hp=Math.min(p.max,p.hp+230+party[0].int);S.msg="施展回復計！";battleView();return setTimeout(enemyTurn,450)}if(i===1&&S.sp<5)return toast("SP不足");if(i===1)S.sp-=5;let es=living(enemies),hits=i===3?living(party).length:1,total=0;for(let h=0;h<hits&&es.length;h++){let t=es[Math.floor(Math.random()*es.length)],d=Math.floor((i===1?130:i===3?65:80)+Math.random()*80+party[0].lv*6);t.hp-=d;total+=d;if(t.hp<=0){t.hp=0;t.dead=true;es=living(enemies)}}S.msg=`${i===1?"烈火席捲敵陣":"我軍發動攻擊"}！造成 ${total} 傷害`;beep(i===1?440:180,.1);battleView();setTimeout(enemyTurn,500)}
function enemyTurn(){if(!living(enemies).length)return victory();let e=living(enemies)[0],ps=living(party),p=ps[Math.floor(Math.random()*ps.length)],d=Math.floor(28+S.chapter*12+Math.random()*55);p.hp-=d;if(p.hp<=0){p.hp=0;p.dead=true}if(!living(party).length){party.forEach(x=>{x.hp=Math.ceil(x.max*.4);x.dead=false});S.gold=Math.max(0,S.gold-50);S.msg="我軍敗退，損失金50。";return setTimeout(world,800)}S.msg=`${e.name}反擊！ ${p.name}損失 ${d} 兵力`;S.turn++;battleView()}
function victory(){let boss=S.bossBattle,g=boss?220:55,xp=boss?180:45;S.gold+=g;S.food+=boss?300:80;party.forEach(p=>{p.exp+=xp;if(p.exp>=p.lv*100){p.exp-=p.lv*100;p.lv++;p.max+=45;p.hp=p.max}});if(boss){if(S.chapter<chapters.length-1){S.chapter++;S.map=S.chapter%2;S.x=7;S.y=6;S.maxSp+=4;S.sp=S.maxSp;S.msg=`主將擊破！進入第${S.chapter+1}章：${chapters[S.chapter]}`;save();setTimeout(world,900)}else{S.scene="ending";ending()}}else{S.msg=`勝利！金+${g} 經驗+${xp}`;setTimeout(world,800)}}
function menu(){S.scene="menu";frame(`<section class="pause"><h2>軍勢</h2>${party.map(p=>`<div><b>${p.name}</b> LV.${p.lv}　兵 ${p.hp}/${p.max}　武器：${p.weapon}</div>`).join("")}<hr>道具：${Object.entries(S.items).map(x=>x.join(" ×")).join("　")}<br>金：${S.gold}　糧：${S.food}<div><button id="sv">儲存</button><button id="back">返回</button><button id="quit">回標題</button></div></section>`);$("#sv").onclick=save;$("#back").onclick=world;$("#quit").onclick=title}
function ending(){frame(`<section class="ending"><h1>天下歸一</h1><p>歷經八章征戰，亂世終告平定。</p><div>${party.map(p=>px(p.name)).join("")}</div><h2>THE END</h2><button id="again">重新開始</button></section>`);$("#again").onclick=()=>{localStorage.removeItem(K);fresh();title()}}
function toast(t){let q=document.createElement("div");q.className="toast";q.textContent=t;document.body.append(q);setTimeout(()=>q.remove(),1000)}
addEventListener("keydown",e=>{let k=e.key.toLowerCase();if(S.scene==="title"&&(e.key==="Enter"||e.key===" ")){fresh();S.scene="world";world()}else if(S.scene==="world"){if(k==="m")menu();else if(k==="s")save();else if(k==="arrowup"||k==="w")walk(0,-1);else if(k==="arrowdown"||k==="s")walk(0,1);else if(k==="arrowleft"||k==="a")walk(-1,0);else if(k==="arrowright"||k==="d")walk(1,0)}else if(S.scene==="battle"){if(e.key==="ArrowUp"){S.menu=(S.menu+5)%6;battleView()}else if(e.key==="ArrowDown"){S.menu=(S.menu+1)%6;battleView()}else if(e.key==="Enter"||e.key===" ")command(S.menu)}else if(S.scene==="menu"&&e.key==="Escape")world()});title();