const N=["關羽","張苞","周瑜","趙雲","姜維"],E=["司馬懿","司馬炎","鄧艾","鍾會","徐晃"];
const C={關羽:"#3d9b68",張苞:"#9a4735",周瑜:"#7250aa",趙雲:"#5d86b8",姜維:"#3f9c88",司馬懿:"#57329b",司馬炎:"#8b3152",鄧艾:"#75543c",鍾會:"#8d503e",徐晃:"#a74432"};
const make=(name,hp,side,i)=>({name,hp,max:hp,side,i,dead:false});let allies=N.map((n,i)=>make(n,[9999,9999,9558,9600,9800][i],"ally",i)),foes=E.map((n,i)=>make(n,[28000,26000,24000,24000,24000][i],"enemy",i));
let sp=247,selected=1,busy=false,msg="選擇指令開始戰鬥",fx=null,round=1;
const skills=[["攻擊",0,900,"slash"],["落雷計",28,1900,"thunder"],["火焰計",24,1650,"fire"],["聖雨",34,-1800,"heal"],["金仙計",45,-2600,"heal"],["陣型",18,1250,"aura"],["謀略",30,2100,"magic"]];
function alive(a){return a.filter(x=>!x.dead)}
function pixel(u){return `<div class="pixel-wrap ${u.side}"><div class="pixel-char" style="--c:${C[u.name]}"><i class="plume"></i><i class="head"></i><i class="body"></i><i class="arm"></i><i class="weapon"></i><i class="leg l"></i><i class="leg r"></i></div></div>`}
function card(u){let p=Math.max(0,u.hp/u.max*100);return `<div class="fighter ${u.side} ${u.dead?"dead":""}" data-name="${u.name}"><div class="stat"><strong>${u.name}</strong><em>${Math.max(0,u.hp)}</em><div class="hp"><span style="width:${p}%"></span></div></div>${pixel(u)}</div>`}
function render(){let a=allies[selected];document.querySelector("#app").innerHTML=`<main><div class="top"><span>蜀漢軍</span><b>三國像素戰記</b><span>魏軍</span></div><div class="stage"><div class="moon"></div><div class="army">${allies.map(card).join("")}</div><div class="vs">VS<br><small>ROUND ${round}</small></div><div class="army">${foes.map(card).join("")}</div><div id="fx" class="${fx||""}"></div></div><div class="hud"><div class="portrait"><div class="bigpixel">${pixel(a)}</div><b>${a.name}</b><small>LV. 28　HP ${Math.max(0,a.hp)}</small></div><div class="menu"><div class="message">SP <b>${sp}</b>　│　${msg}</div><div class="grid">${skills.map((s,i)=>`<button data-s="${i}" ${busy?"disabled":""}><i>▶</i>${s[0]}<small>SP ${s[1]}</small></button>`).join("")}</div></div></div><footer>v1.1.0.0 · Original CSS Pixel Art · Click a hero to change commander</footer></main>`;
document.querySelectorAll("button").forEach(x=>x.onclick=()=>act(+x.dataset.s));document.querySelectorAll(".fighter.ally").forEach((x,i)=>x.onclick=()=>{if(!allies[i].dead){selected=i;msg=`${allies[i].name} 準備出戰`;render()}})}
function effect(type,target){fx=type;render();setTimeout(()=>{fx=null;render()},480);let el=document.querySelector(`[data-name="${target.name}"]`);if(el)el.classList.add(type==="heal"?"healed":"hit")}
function act(i){if(busy)return;let [name,cost,power,type]=skills[i],actor=allies[selected];if(actor.dead){msg="此武將已無法戰鬥";render();return}if(sp<cost){msg="SP 不足！";render();return}sp-=cost;busy=true;if(power<0){let t=alive(allies).sort((a,b)=>a.hp/a.max-b.hp/b.max)[0];let n=Math.min(-power,t.max-t.hp);t.hp+=n;msg=`${actor.name}施展${name}，${t.name}恢復 ${n} HP`;effect("heal",t)}else{let es=alive(foes),t=es[Math.floor(Math.random()*es.length)],d=Math.floor(power*.78+Math.random()*power*.44);t.hp-=d;if(t.hp<=0){t.hp=0;t.dead=true}msg=`${actor.name}施展${name}！ ${t.name} -${d}`;effect(type,t)}setTimeout(()=>{if(!alive(foes).length){msg="大勝！魏軍全滅！";busy=false;render();return}enemyTurn()},700)}
function enemyTurn(){let es=alive(foes),as=alive(allies),e=es[Math.floor(Math.random()*es.length)],t=as[Math.floor(Math.random()*as.length)],d=Math.floor(500+Math.random()*750);t.hp-=d;if(t.hp<=0){t.hp=0;t.dead=true;if(t===allies[selected]){let ni=allies.findIndex(x=>!x.dead);if(ni>=0)selected=ni}}msg=`${e.name}反擊！ ${t.name} -${d}`;round++;effect("enemyfx",t);setTimeout(()=>{busy=false;if(!alive(allies).length)msg="全軍覆沒… 點重新整理再戰";render()},500)}
render();